=== a00909032/lab07/data/week.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT timetable (course)+>
<!ATTLIST timetable
day (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
>

<!ELEMENT course (name, instructor, room, period, day?)>
<!ATTLIST course
type (lecture|lab|tutorial) #REQUIRED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT period (#PCDATA)>
<!ATTLIST period
start (830|930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
duration (1|2|3) #REQUIRED
>

=== a00909032/lab07/data/week.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
ACIT 4850
Damian Kim
Pablo Ramos

Week perspective
-->

<!DOCTYPE timetable SYSTEM 'week.dtd'>


    <timetable day="Monday">
        <course type="tutorial">
            <name>ACIT 4770</name>
            <instructor>Trevor Lord</instructor>
            <room>SE12 306</room>
            <period start="1330" duration="2"/>
        </course>
        <course type="lecture">
            <name>ACIT 4910</name>
            <instructor>Richard Chau</instructor>
            <room>SW9 206</room>
            <period start="1530" duration="1"/>
        </course>
        <course type="lecture">
            <name>ACIT 4650</name>
            <instructor>Medhat Elmasry</instructor>
            <room>SE6 205</room>
            <period start="1430" duration="2"/>
        </course>
    </timetable>
